"use client";

import {
  Sparkles,
  AlertTriangle,
  CheckCircle,
  ArrowRight,
  TrendingUp,
} from "lucide-react";

import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";

interface Summary {
  id: string;
  executiveSummary: string | null;
  keyPoints: string[];
  risks: string[];
  decisions: string[];
  nextSteps: string[];
  overallSentiment: number | null;
  generatedByModel: string;
}

interface SummaryPanelProps {
  summary: Summary;
}

function getSentimentLabel(sentiment: number | null): {
  label: string;
  color: string;
} {
  if (sentiment === null) return { label: "Unknown", color: "secondary" };
  if (sentiment > 0.3) return { label: "Positive", color: "bg-green-100 text-green-800" };
  if (sentiment < -0.3) return { label: "Negative", color: "bg-red-100 text-red-800" };
  return { label: "Neutral", color: "bg-yellow-100 text-yellow-800" };
}

export function SummaryPanel({ summary }: SummaryPanelProps) {
  const sentiment = getSentimentLabel(summary.overallSentiment);

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5" />
            AI Summary
          </CardTitle>
          <Badge variant="outline" className={sentiment.color}>
            <TrendingUp className="mr-1 h-3 w-3" />
            {sentiment.label}
          </Badge>
        </div>
        <p className="text-xs text-muted-foreground">
          Generated by {summary.generatedByModel}
        </p>
      </CardHeader>
      <CardContent className="space-y-6">
        {summary.executiveSummary && (
          <div>
            <h4 className="mb-2 text-sm font-semibold">Executive Summary</h4>
            <p className="text-sm text-muted-foreground leading-relaxed">
              {summary.executiveSummary}
            </p>
          </div>
        )}

        {summary.keyPoints.length > 0 && (
          <>
            <Separator />
            <div>
              <h4 className="mb-2 flex items-center gap-2 text-sm font-semibold">
                <CheckCircle className="h-4 w-4 text-green-600" />
                Key Points
              </h4>
              <ul className="space-y-2">
                {summary.keyPoints.map((point, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm">
                    <span className="mt-1 h-1.5 w-1.5 rounded-full bg-primary" />
                    {point}
                  </li>
                ))}
              </ul>
            </div>
          </>
        )}

        {summary.decisions.length > 0 && (
          <>
            <Separator />
            <div>
              <h4 className="mb-2 flex items-center gap-2 text-sm font-semibold">
                <CheckCircle className="h-4 w-4 text-blue-600" />
                Decisions Made
              </h4>
              <ul className="space-y-2">
                {summary.decisions.map((decision, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm">
                    <span className="mt-1 h-1.5 w-1.5 rounded-full bg-blue-500" />
                    {decision}
                  </li>
                ))}
              </ul>
            </div>
          </>
        )}

        {summary.risks.length > 0 && (
          <>
            <Separator />
            <div>
              <h4 className="mb-2 flex items-center gap-2 text-sm font-semibold">
                <AlertTriangle className="h-4 w-4 text-orange-600" />
                Risks & Concerns
              </h4>
              <ul className="space-y-2">
                {summary.risks.map((risk, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-orange-700">
                    <span className="mt-1 h-1.5 w-1.5 rounded-full bg-orange-500" />
                    {risk}
                  </li>
                ))}
              </ul>
            </div>
          </>
        )}

        {summary.nextSteps.length > 0 && (
          <>
            <Separator />
            <div>
              <h4 className="mb-2 flex items-center gap-2 text-sm font-semibold">
                <ArrowRight className="h-4 w-4 text-purple-600" />
                Next Steps
              </h4>
              <ul className="space-y-2">
                {summary.nextSteps.map((step, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm">
                    <span className="mt-1 h-1.5 w-1.5 rounded-full bg-purple-500" />
                    {step}
                  </li>
                ))}
              </ul>
            </div>
          </>
        )}
      </CardContent>
    </Card>
  );
}
